name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: npm install, build
        
        run: npm install

      - name: Run linter

        run: |
          make lint
      - name: Run test

        run: |
          make test