name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ubuntu
        uses: hexlet/project-action@release
    
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: npm install, build
        
        run: npm install

      - name: Run linter
        # Run Linter
        run: |
          make lint